#!/bin/bash
mkdir /tmp/my_first_directory
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~


~
~
~
~
~
~
                                                                                             1,0-1         All

